# Generated by Django 4.2.1 on 2023-09-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0002_alter_docente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='estado',
            field=models.CharField(max_length=1),
        ),
    ]
