# Generated by Django 4.2.7 on 2023-12-10 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0004_asistencia_responsable_alter_asistencia_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
